apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - image: hello-nodejs
        imagePullPolicy: Always
        name: node-web-app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          periodSeconds: 5
